# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  ## push:
  ##  branches: [ "master" ]
  ## pull_request:
  ##  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: foundationdb/build:centos7-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p build_output
          source /opt/rh/devtoolset-8/enable && source /opt/rh/rh-python38/enable && cmake -DFDB_RELEASE=ON -DBUILD_AZURE_BACKUP=ON -G Ninja ../foundationdb
          ninja -j2
          cpack -G DEB
          ls -laR packages
          rm -rf packages/bin
          rm -rf packages/*versioned*
          rm -rf packages/*.tar.gz
          rm -rf packages/*ddeb*
          
      # Save built packages.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            $GITHUB_WORKSPACE/build_output/packages

